### ISSUE TITLE
Preload not working on hover

### ISSUE THREAD

**Issue by RubiousShaun** [swup/preload-plugin#1]
Hi, I'm moving a site from the previous version of swup to the new one, and I've added the preload plugin but it doesn't seem to animate on hover anymore. Has this functionality been removed/broken?

**Comment by gmrchk** [comment]
Hi, I guess you mean not preloading on hover. I checked and it was caused by a little typo I had. Update plugin and all should be good.

Thanks for reporting 👍

**Comment by RubiousShaun** [comment]
Great thanks!
