### ISSUE TITLE
`options.preloadVisibleLinks.enabled` not being applied automatically

### ISSUE THREAD

**Issue by hirasso** [swup/preload-plugin#102]
**Description of the issue**

IMO it's save to assume that initializing preload plugin like this:

```js
new SwupPreloadPlugin({
	preloadVisibleLinks: {
		delay: 0,
	},
})
```
...should automatically set `preloadVisibleLinks.enabled` to `true`. [The plugin docs](https://swup.js.org/plugins/preload-plugin/#preload-visible-links) also suggest that behavior.

This is not the case right now. What's your opinion here @daun ? 

**Before creating this issue...**

- [x] Have you provided all helpful information available?
- [x] Have you checked closed issues for similar/related problems?

**Comment by daun** [comment]
That should definitely work, I agree! Feel free to open a PR that fixes it, otherwise I might get to it later this week.
