### ISSUE TITLE
[Bug]: External links are not being properly ignored on hover

### ISSUE THREAD

**Issue by hirasso** [swup/preload-plugin#118]
### What did you expect? 🧐

If I am on a website https://example.com and I have an external link on that site, for example:

```html
<a href="https://www.instagram.com/followme">@followme</a>
```

I'd expect preload plugin to ignore that link when I hover over it.

### What actually happened? 😵‍💫

Currently the plugin will attempt to preload this URL:

```
https://example.com/{{path/of/external/link}}
```

So based on the example above this: https://example.com/followme

I suspect the problem lies within `Location.fromElement` that is being used here:

https://github.com/swup/preload-plugin/blob/604d381168e9a51b76bf6f5a793436932e772ae1/src/index.ts#L260

That function doesn't check if the provided URL is actually an internal URL or not. 

I'll investigate further.

### Swup and plugin versions 📝

```shell
❯ npm list | grep swup
├── @swup/a11y-plugin@4.5.0
├── @swup/body-class-plugin@3.1.2
├── @swup/debug-plugin@4.0.4
├── @swup/fragment-plugin@0.3.7
├── @swup/head-plugin@2.1.2
├── @swup/preload-plugin@3.2.7
├── @swup/progress-plugin@3.1.2
├── @swup/scroll-plugin@3.3.1
├── swup@4.5.1
```

### URL to minimal reproduction 🔗

n/a

### Checked all these? 📚

- [X] I have read and searched the [official docs](https://swup.js.org)
- [X] I have checked [discussions](https://github.com/orgs/swup/discussions) and [existing issues](https://github.com/issues?q=is:issue+org:swup) for related problems
- [X] I agree to follow this project's [Code of Conduct](https://github.com/swup/.github/blob/master/CODE_OF_CONDUCT.md)
- [X] I have provided all necessary information to the best of my knowledge

**Comment by daun** [comment]
Good catch, this should probably be `href` instead of `url`.

I've started a branch for functional tests some time ago in December. Time to finish that so we find these types of issues earlier or avoid them at all.

**Comment by daun** [comment]
Since the plugin defers to swup itself for checking whether to ignore a link or not, using `href` should be enough.

**Comment by hirasso** [comment]
But is that actually really what we want? It seems like pretty unintuitive behavior of `Location.url` to me. How about we change the `Location.url` as proposed in [this PR](https://github.com/swup/swup/pull/867)?

**Comment by daun** [comment]
I'd say that's what we want. The `url` property is shorthand for `path` + `search`, which in a normal `URL` object also don't care about the origin. I'd suggest a new `local` getter on the location object and making sure we're using that throughout the codebase, e.g. `if (!location.local) return;`. Returning a full href from `url` in one case and a local path in another case would make things more confusing in my opinion.

```js
class Location {
  get local() {
    return this.origin !== window.location.origin;
  }
}

**Comment by daun** [comment]
The naming of the `url` property is a bit unfortunate, but if I remember correctly, we just haven't managed to find the perfect name for it when creating the `Location` abstraction. The intention was to have the `path` part including all query params.
