### ISSUE TITLE
Preload-Plugin Compromises SSL Certificate and creates time-out issues in WP 

### ISSUE THREAD

**Issue by PietM** [swup/preload-plugin#2]
Good greetings! 
Love swup. I'm using v2 and noticed that when using the Preload plugin, the SSL lock disappears from the browser and time-outs are prompted in Wordpress. These issues are resolved once the Preload plugin is disabled/removed. 

Any ideas as to why this is the case? 
Would love to continue using the preload plugin, but these are major interruptions to workflow. 

Please let me know! 

Kind regards

**Comment by gmrchk** [comment]
Hi @PietM,

This is an interesting problem and something that didn't come up so far. That probably means that it's a new problem or the preload functionality is not at fault. 

I'm guessing this could happen in case swup preloads pages with `http` (not `https`), but the plugin should preload whatever link it's given (so wrong link could cause this). Another cause could be the loading of the plugin itself from an insecure place, but that's all I can say from the description, as preload works fine for me on https (but it's not a WP site). 

Do you think you could provide a hosted demo where this problem can be seen?
