### ISSUE TITLE
Possibility to ignore a certain link?

### ISSUE THREAD

**Issue by sstottelaar** [swup/preload-plugin#9]
First of all, great work on Swup.js!

I was wondering if it's possible to ignore a certain link from preloading? Ideally via a data attribute. My website has multiple links to PDF files, these can't be preloaded which throws errors in the console.

Any guidance would be appreciated!

**Comment by gmrchk** [comment]
Hey, using `data-no-swup` or changing [this option](https://swup.js.org/options#link-selector) is what you're looking for.
