### ISSUE TITLE
dist/index.module.js is missing

### ISSUE THREAD

**Issue by mevanloon** [swup/preload-plugin#93]
Parcel gives me this error on this package only. It works perfectly in 3.2.0 when I'm forcing it, so I'm assuming a regression.

**Comment by daun** [comment]
You're right, that's a regression! Working on a fix.

**Comment by daun** [comment]
Should be fixed in [3.2.2](https://github.com/swup/preload-plugin/releases/tag/3.2.2) — let us know if it isn't and thanks for reporting!
