### ISSUE TITLE
requestIdleCallback not available in Safari

### ISSUE THREAD

**Issue by jorisnoo** [swup/preload-plugin#98]
Although the plugin seems to work just fine, the following error is being thrown in Safari: `Unhandled Promise Rejection: ReferenceError: Can't find variable: requestIdleCallback`, as the browser does [not support](https://developer.mozilla.org/en-US/docs/Web/API/Window/requestIdleCallback) requestIdleCallback.

See a related issue: https://github.com/remix-run/indie-stack/issues/124 where a  possible fallback is being suggested.

Thanks for all your effort on this, much appreciated!

**Comment by daun** [comment]
Wow, I just checked the [caniuse page for requestIdleCallback](https://caniuse.com/requestidlecallback) and Safari has had support for this for more than three years now but it's still behind a feature flag 😩 Falling back to `setTimeout` should work here as well. Thanks for reporting!

**Comment by daun** [comment]
Fixed and released as [3.2.3](https://github.com/swup/preload-plugin/releases/tag/3.2.3), thanks again for reporting.
